import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { LAYOUT_STYLES } from "./lib/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main mb-20`}>
        <Header className={`${LAYOUT_STYLES}`} />

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
